### ISSUE TITLE
Moving logo, invisible text & unskinned timers.

### ISSUE THREAD

**Issue by jackiedorland** [omnibombulator/Flarepunch#1]
How would i move the "Flarepunch" logo from being top-centered to the left and inline with the other icons, while keeping them all centered? I'd really like to do this because the logo in the middle of the screen doesn't look great to me. 
Also: Is there any way to bring back the Casual/Comp coins in the HUD

Thanks!

**Comment by jackiedorland** [comment]
Another thing: How can i change the Flarepunch logo to the TF2 Logo

**Comment by jackiedorland** [comment]
The text is also invisible/distorted, screenshot below: 
![a5540c](https://user-images.githubusercontent.com/16177268/45259596-7d1c2000-b39e-11e8-891b-b6ee723a3206.png)

**Comment by jackiedorland** [comment]
Another picture: 
![42a472](https://user-images.githubusercontent.com/16177268/45259602-b18fdc00-b39e-11e8-80b3-f290e6205473.png)

**Comment by jackiedorland** [comment]
And the Warmup Timer is left unskinned. Was this intentional?
![42dba0](https://user-images.githubusercontent.com/16177268/45259748-abe7c580-b3a1-11e8-86de-5fa746c2891d.png)

**Comment by omnibombulator** [comment]
1. The Main Menu is put together in a way where if you move the logo, the other parts will follow. They are pinned to the logo iirc.
2. You can change the logo by using a Font that has the TF2 logo symbol included, then change the Font and the labeltext of the logo to reflect the new font.
3. The text on the item boxes are supposed to be that way. I did it intentionally.
4. It was not done intentionally. This is one of the things I missed I have yet to fix.

**Comment by jackiedorland** [comment]
How would i change the font including the TF logo? Does the icons being pinned to the logo mean i cannot move the logo to the left?

**Comment by jackiedorland** [comment]
Another thing: Is there any way to remove the Dim Effect from the Find A Game button?

**Comment by jackiedorland** [comment]
Is there a way to change the color of the "Your match is ready!" tooltip? Couldn't find it in the colorscheme.res file. 
![fc4929](https://user-images.githubusercontent.com/16177268/45266369-3246ea80-b428-11e8-9951-80ba118bb8f5.png)
